<?php
declare(strict_types=1);

require_once __DIR__ . "/BaseRepository.php";

class SettingsRepository extends BaseRepository
{
  public function getProductStats(): array
  {
    $row = $this->fetchOne(
      "SELECT
        SUM(CASE WHEN status = 'Active' THEN 1 ELSE 0 END) AS active,
        SUM(CASE WHEN status = 'Inactive' THEN 1 ELSE 0 END) AS archived
       FROM loan_products"
    ) ?? [];

    return [
      "active" => (int) ($row["active"] ?? 0),
      "pending_updates" => 0,
      "draft" => 0,
      "archived" => (int) ($row["archived"] ?? 0),
    ];
  }

  public function getLoanProducts(?string $status = null): array
  {
    $sql = "SELECT id, name, code, description, interest_rate, service_charge, status
            FROM loan_products";
    $params = [];

    if ($status === "Active" || $status === "Inactive") {
      $sql .= " WHERE status = :status";
      $params["status"] = $status;
    }

    $sql .= " ORDER BY created_at DESC";

    return $this->fetchAll($sql, $params);
  }

  public function getLoanProductById(int $id): ?array
  {
    return $this->fetchOne(
      "SELECT *
       FROM loan_products
       WHERE id = ?",
      [$id]
    );
  }

  public function createLoanProduct(array $payload): int
  {
    $this->execute(
      "INSERT INTO loan_products (
        name,
        code,
        description,
        status,
        loan_type,
        promissory_note,
        max_loan_amount,
        ceiling_loan_product,
        max_loan_count,
        grouping,
        cost_center,
        borrower_type_default,
        require_security,
        default_security,
        proceeds_type_default,
        enable_deed_assignment,
        required_no_employees,
        required_coborrower,
        required_comakers,
        employee_loan,
        term_unit,
        term_unit_flexible,
        fixed_number_days,
        fixed_number_days_flexible,
        default_term,
        default_term_flexible,
        maximum_term,
        interest_rate,
        interest_rate_flexible,
        recompute_interest,
        interest_basis_computation,
        interest_basis_flexible,
        interest_computation,
        interest_computation_flexible,
        interest_rate_minimum,
        days_in_year,
        penalty_per_amort_fixed_rate,
        penalty_per_amort_fixed_amount,
        penalty_per_amort_running_rate,
        penalty_per_amort_grace_days,
        penalty_per_amort_basis,
        penalty_after_maturity_fixed_rate,
        penalty_after_maturity_fixed_amount,
        penalty_after_maturity_running_rate,
        penalty_after_maturity_grace_days,
        penalty_after_maturity_basis,
        disregard_payments_after_maturity,
        include_amort_penalty,
        past_due_interest_rate,
        past_due_interest_basis,
        past_due_disregard_payments,
        penalty_gl_account,
        grace_period_option,
        secured_approval_min,
        secured_approval_max,
        secured_approver_count,
        unsecured_approval_min,
        unsecured_approval_max,
        unsecured_approver_count,
        service_charge_used,
        savings_discounted_used,
        grt_used,
        insurance_used,
        notarial_used,
        doc_stamp_used,
        inspection_fee_used,
        filing_fee_used,
        processing_fee_used,
        ctr_fund_used,
        insurance2_used,
        deduction8_used,
        deduction9_used,
        service_charge_amortized,
        savings_amortized,
        amort1,
        amort2,
        amort_date_adjustment,
        amort_adjust_on_holidays,
        amortization_grace_period,
        auto_debit_amortization,
        savings_holdout_value,
        savings_holdout_basis,
        cure_period_daily,
        cure_period_weekly,
        cure_period_semi_monthly,
        cure_period_monthly,
        cure_period_quarterly,
        cure_period_semi_annual,
        cure_period_annual,
        cure_period_lumpsum,
        enable_individual_cure_period,
        enable_release_tagging,
        cash_disbursed_by_teller,
        security_dependent_pns,
        acl_exempted,
        acl_assessment,
        comakership_limit,
        collection_list_display,
        collection_list_orientation,
        balance_to_show,
        reflect_date_granted,
        reflect_loan_amount,
        reflect_savings_balance,
        reflect_duedate,
        signature_on_collection_list,
        sms_language,
        sms_free,
        sms_show_unpaid_amorts,
        service_charge
      ) VALUES (
        :name,
        :code,
        :description,
        :status,
        :loan_type,
        :promissory_note,
        :max_loan_amount,
        :ceiling_loan_product,
        :max_loan_count,
        :grouping,
        :cost_center,
        :borrower_type_default,
        :require_security,
        :default_security,
        :proceeds_type_default,
        :enable_deed_assignment,
        :required_no_employees,
        :required_coborrower,
        :required_comakers,
        :employee_loan,
        :term_unit,
        :term_unit_flexible,
        :fixed_number_days,
        :fixed_number_days_flexible,
        :default_term,
        :default_term_flexible,
        :maximum_term,
        :interest_rate,
        :interest_rate_flexible,
        :recompute_interest,
        :interest_basis_computation,
        :interest_basis_flexible,
        :interest_computation,
        :interest_computation_flexible,
        :interest_rate_minimum,
        :days_in_year,
        :penalty_per_amort_fixed_rate,
        :penalty_per_amort_fixed_amount,
        :penalty_per_amort_running_rate,
        :penalty_per_amort_grace_days,
        :penalty_per_amort_basis,
        :penalty_after_maturity_fixed_rate,
        :penalty_after_maturity_fixed_amount,
        :penalty_after_maturity_running_rate,
        :penalty_after_maturity_grace_days,
        :penalty_after_maturity_basis,
        :disregard_payments_after_maturity,
        :include_amort_penalty,
        :past_due_interest_rate,
        :past_due_interest_basis,
        :past_due_disregard_payments,
        :penalty_gl_account,
        :grace_period_option,
        :secured_approval_min,
        :secured_approval_max,
        :secured_approver_count,
        :unsecured_approval_min,
        :unsecured_approval_max,
        :unsecured_approver_count,
        :service_charge_used,
        :savings_discounted_used,
        :grt_used,
        :insurance_used,
        :notarial_used,
        :doc_stamp_used,
        :inspection_fee_used,
        :filing_fee_used,
        :processing_fee_used,
        :ctr_fund_used,
        :insurance2_used,
        :deduction8_used,
        :deduction9_used,
        :service_charge_amortized,
        :savings_amortized,
        :amort1,
        :amort2,
        :amort_date_adjustment,
        :amort_adjust_on_holidays,
        :amortization_grace_period,
        :auto_debit_amortization,
        :savings_holdout_value,
        :savings_holdout_basis,
        :cure_period_daily,
        :cure_period_weekly,
        :cure_period_semi_monthly,
        :cure_period_monthly,
        :cure_period_quarterly,
        :cure_period_semi_annual,
        :cure_period_annual,
        :cure_period_lumpsum,
        :enable_individual_cure_period,
        :enable_release_tagging,
        :cash_disbursed_by_teller,
        :security_dependent_pns,
        :acl_exempted,
        :acl_assessment,
        :comakership_limit,
        :collection_list_display,
        :collection_list_orientation,
        :balance_to_show,
        :reflect_date_granted,
        :reflect_loan_amount,
        :reflect_savings_balance,
        :reflect_duedate,
        :signature_on_collection_list,
        :sms_language,
        :sms_free,
        :sms_show_unpaid_amorts,
        :service_charge
      )",
      $payload
    );

    return (int) $this->db()->lastInsertId();
  }

  public function updateLoanProduct(int $id, array $payload): void
  {
    $payload["id"] = $id;
    $this->execute(
      "UPDATE loan_products SET
        name = :name,
        code = :code,
        description = :description,
        status = :status,
        loan_type = :loan_type,
        promissory_note = :promissory_note,
        max_loan_amount = :max_loan_amount,
        ceiling_loan_product = :ceiling_loan_product,
        max_loan_count = :max_loan_count,
        grouping = :grouping,
        cost_center = :cost_center,
        borrower_type_default = :borrower_type_default,
        require_security = :require_security,
        default_security = :default_security,
        proceeds_type_default = :proceeds_type_default,
        enable_deed_assignment = :enable_deed_assignment,
        required_no_employees = :required_no_employees,
        required_coborrower = :required_coborrower,
        required_comakers = :required_comakers,
        employee_loan = :employee_loan,
        term_unit = :term_unit,
        term_unit_flexible = :term_unit_flexible,
        fixed_number_days = :fixed_number_days,
        fixed_number_days_flexible = :fixed_number_days_flexible,
        default_term = :default_term,
        default_term_flexible = :default_term_flexible,
        maximum_term = :maximum_term,
        interest_rate = :interest_rate,
        interest_rate_flexible = :interest_rate_flexible,
        recompute_interest = :recompute_interest,
        interest_basis_computation = :interest_basis_computation,
        interest_basis_flexible = :interest_basis_flexible,
        interest_computation = :interest_computation,
        interest_computation_flexible = :interest_computation_flexible,
        interest_rate_minimum = :interest_rate_minimum,
        days_in_year = :days_in_year,
        penalty_per_amort_fixed_rate = :penalty_per_amort_fixed_rate,
        penalty_per_amort_fixed_amount = :penalty_per_amort_fixed_amount,
        penalty_per_amort_running_rate = :penalty_per_amort_running_rate,
        penalty_per_amort_grace_days = :penalty_per_amort_grace_days,
        penalty_per_amort_basis = :penalty_per_amort_basis,
        penalty_after_maturity_fixed_rate = :penalty_after_maturity_fixed_rate,
        penalty_after_maturity_fixed_amount = :penalty_after_maturity_fixed_amount,
        penalty_after_maturity_running_rate = :penalty_after_maturity_running_rate,
        penalty_after_maturity_grace_days = :penalty_after_maturity_grace_days,
        penalty_after_maturity_basis = :penalty_after_maturity_basis,
        disregard_payments_after_maturity = :disregard_payments_after_maturity,
        include_amort_penalty = :include_amort_penalty,
        past_due_interest_rate = :past_due_interest_rate,
        past_due_interest_basis = :past_due_interest_basis,
        past_due_disregard_payments = :past_due_disregard_payments,
        penalty_gl_account = :penalty_gl_account,
        grace_period_option = :grace_period_option,
        secured_approval_min = :secured_approval_min,
        secured_approval_max = :secured_approval_max,
        secured_approver_count = :secured_approver_count,
        unsecured_approval_min = :unsecured_approval_min,
        unsecured_approval_max = :unsecured_approval_max,
        unsecured_approver_count = :unsecured_approver_count,
        service_charge_used = :service_charge_used,
        savings_discounted_used = :savings_discounted_used,
        grt_used = :grt_used,
        insurance_used = :insurance_used,
        notarial_used = :notarial_used,
        doc_stamp_used = :doc_stamp_used,
        inspection_fee_used = :inspection_fee_used,
        filing_fee_used = :filing_fee_used,
        processing_fee_used = :processing_fee_used,
        ctr_fund_used = :ctr_fund_used,
        insurance2_used = :insurance2_used,
        deduction8_used = :deduction8_used,
        deduction9_used = :deduction9_used,
        service_charge_amortized = :service_charge_amortized,
        savings_amortized = :savings_amortized,
        amort1 = :amort1,
        amort2 = :amort2,
        amort_date_adjustment = :amort_date_adjustment,
        amort_adjust_on_holidays = :amort_adjust_on_holidays,
        amortization_grace_period = :amortization_grace_period,
        auto_debit_amortization = :auto_debit_amortization,
        savings_holdout_value = :savings_holdout_value,
        savings_holdout_basis = :savings_holdout_basis,
        cure_period_daily = :cure_period_daily,
        cure_period_weekly = :cure_period_weekly,
        cure_period_semi_monthly = :cure_period_semi_monthly,
        cure_period_monthly = :cure_period_monthly,
        cure_period_quarterly = :cure_period_quarterly,
        cure_period_semi_annual = :cure_period_semi_annual,
        cure_period_annual = :cure_period_annual,
        cure_period_lumpsum = :cure_period_lumpsum,
        enable_individual_cure_period = :enable_individual_cure_period,
        enable_release_tagging = :enable_release_tagging,
        cash_disbursed_by_teller = :cash_disbursed_by_teller,
        security_dependent_pns = :security_dependent_pns,
        acl_exempted = :acl_exempted,
        acl_assessment = :acl_assessment,
        comakership_limit = :comakership_limit,
        collection_list_display = :collection_list_display,
        collection_list_orientation = :collection_list_orientation,
        balance_to_show = :balance_to_show,
        reflect_date_granted = :reflect_date_granted,
        reflect_loan_amount = :reflect_loan_amount,
        reflect_savings_balance = :reflect_savings_balance,
        reflect_duedate = :reflect_duedate,
        signature_on_collection_list = :signature_on_collection_list,
        sms_language = :sms_language,
        sms_free = :sms_free,
        sms_show_unpaid_amorts = :sms_show_unpaid_amorts,
        service_charge = :service_charge
      WHERE id = :id",
      $payload
    );
  }

  public function getRecommendedProducts(int $limit = 2): array
  {
    $limit = max(1, $limit);
    return $this->fetchAll(
      "SELECT id, name, interest_rate, service_charge, status
       FROM loan_products
       WHERE status = 'Active'
       ORDER BY created_at DESC
       LIMIT {$limit}"
    );
  }
}
