ALTER TABLE loan_products
  MODIFY interest_rate DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  MODIFY service_charge DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  ADD COLUMN code VARCHAR(60) NULL AFTER name,
  ADD COLUMN description VARCHAR(255) NULL AFTER code,
  ADD COLUMN loan_type VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER status,
  ADD COLUMN promissory_note VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER loan_type,
  ADD COLUMN max_loan_amount DECIMAL(12,2) NULL AFTER promissory_note,
  ADD COLUMN ceiling_loan_product DECIMAL(12,2) NULL AFTER max_loan_amount,
  ADD COLUMN max_loan_count INT UNSIGNED NULL AFTER ceiling_loan_product,
  ADD COLUMN grouping VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER max_loan_count,
  ADD COLUMN cost_center VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER grouping,
  ADD COLUMN borrower_type_default VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER cost_center,
  ADD COLUMN require_security VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER borrower_type_default,
  ADD COLUMN default_security VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER require_security,
  ADD COLUMN proceeds_type_default VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER default_security,
  ADD COLUMN enable_deed_assignment VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER proceeds_type_default,
  ADD COLUMN required_no_employees TINYINT(1) NOT NULL DEFAULT 0 AFTER enable_deed_assignment,
  ADD COLUMN required_coborrower TINYINT(1) NOT NULL DEFAULT 0 AFTER required_no_employees,
  ADD COLUMN required_comakers INT UNSIGNED NULL AFTER required_coborrower,
  ADD COLUMN employee_loan VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER required_comakers,
  ADD COLUMN term_unit VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER employee_loan,
  ADD COLUMN term_unit_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER term_unit,
  ADD COLUMN fixed_number_days INT UNSIGNED NULL AFTER term_unit_flexible,
  ADD COLUMN fixed_number_days_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER fixed_number_days,
  ADD COLUMN default_term INT UNSIGNED NULL AFTER fixed_number_days_flexible,
  ADD COLUMN default_term_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER default_term,
  ADD COLUMN maximum_term INT UNSIGNED NULL AFTER default_term_flexible,
  ADD COLUMN interest_rate_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER interest_rate,
  ADD COLUMN recompute_interest TINYINT(1) NOT NULL DEFAULT 0 AFTER interest_rate_flexible,
  ADD COLUMN interest_basis_computation VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER recompute_interest,
  ADD COLUMN interest_basis_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER interest_basis_computation,
  ADD COLUMN interest_computation VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER interest_basis_flexible,
  ADD COLUMN interest_computation_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER interest_computation,
  ADD COLUMN interest_rate_minimum DECIMAL(8,4) NOT NULL DEFAULT 0.0000 AFTER interest_computation_flexible,
  ADD COLUMN days_in_year INT UNSIGNED NOT NULL DEFAULT 360 AFTER interest_rate_minimum,
  ADD COLUMN penalty_per_amort_fixed_rate DECIMAL(8,4) NULL AFTER days_in_year,
  ADD COLUMN penalty_per_amort_fixed_amount DECIMAL(12,2) NULL AFTER penalty_per_amort_fixed_rate,
  ADD COLUMN penalty_per_amort_running_rate DECIMAL(8,4) NULL AFTER penalty_per_amort_fixed_amount,
  ADD COLUMN penalty_per_amort_grace_days INT UNSIGNED NULL AFTER penalty_per_amort_running_rate,
  ADD COLUMN penalty_per_amort_basis VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER penalty_per_amort_grace_days,
  ADD COLUMN penalty_after_maturity_fixed_rate DECIMAL(8,4) NULL AFTER penalty_per_amort_basis,
  ADD COLUMN penalty_after_maturity_fixed_amount DECIMAL(12,2) NULL AFTER penalty_after_maturity_fixed_rate,
  ADD COLUMN penalty_after_maturity_running_rate DECIMAL(8,4) NULL AFTER penalty_after_maturity_fixed_amount,
  ADD COLUMN penalty_after_maturity_grace_days INT UNSIGNED NULL AFTER penalty_after_maturity_running_rate,
  ADD COLUMN penalty_after_maturity_basis VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER penalty_after_maturity_grace_days,
  ADD COLUMN disregard_payments_after_maturity TINYINT(1) NOT NULL DEFAULT 0 AFTER penalty_after_maturity_basis,
  ADD COLUMN include_amort_penalty TINYINT(1) NOT NULL DEFAULT 0 AFTER disregard_payments_after_maturity,
  ADD COLUMN past_due_interest_rate DECIMAL(8,4) NULL AFTER include_amort_penalty,
  ADD COLUMN past_due_interest_basis VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER past_due_interest_rate,
  ADD COLUMN past_due_disregard_payments TINYINT(1) NOT NULL DEFAULT 0 AFTER past_due_interest_basis,
  ADD COLUMN penalty_gl_account VARCHAR(120) NULL AFTER past_due_disregard_payments,
  ADD COLUMN grace_period_option VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER penalty_gl_account,
  ADD COLUMN secured_approval_min DECIMAL(12,2) NULL AFTER grace_period_option,
  ADD COLUMN secured_approval_max DECIMAL(12,2) NULL AFTER secured_approval_min,
  ADD COLUMN secured_approver_count INT UNSIGNED NOT NULL DEFAULT 1 AFTER secured_approval_max,
  ADD COLUMN unsecured_approval_min DECIMAL(12,2) NULL AFTER secured_approver_count,
  ADD COLUMN unsecured_approval_max DECIMAL(12,2) NULL AFTER unsecured_approval_min,
  ADD COLUMN unsecured_approver_count INT UNSIGNED NOT NULL DEFAULT 1 AFTER unsecured_approval_max,
  ADD COLUMN service_charge_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER unsecured_approver_count,
  ADD COLUMN savings_discounted_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER service_charge_used,
  ADD COLUMN grt_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER savings_discounted_used,
  ADD COLUMN insurance_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER grt_used,
  ADD COLUMN insurance_name VARCHAR(120) NULL AFTER insurance_used,
  ADD COLUMN insurance_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER insurance_name,
  ADD COLUMN insurance_provider_default VARCHAR(120) NOT NULL DEFAULT 'ICISP' AFTER insurance_flexible,
  ADD COLUMN insurance_table VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER insurance_provider_default,
  ADD COLUMN insurance_printing_form VARCHAR(120) NOT NULL DEFAULT 'Yes' AFTER insurance_table,
  ADD COLUMN insurance_gl_account VARCHAR(160) NULL AFTER insurance_printing_form,
  ADD COLUMN insurance_product VARCHAR(120) NOT NULL DEFAULT 'None' AFTER insurance_gl_account,
  ADD COLUMN notarial_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER insurance_product,
  ADD COLUMN doc_stamp_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER notarial_used,
  ADD COLUMN inspection_fee_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER doc_stamp_used,
  ADD COLUMN filing_fee_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER inspection_fee_used,
  ADD COLUMN processing_fee_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER filing_fee_used,
  ADD COLUMN processing_fee_name VARCHAR(120) NULL AFTER processing_fee_used,
  ADD COLUMN processing_fee_bracket_option VARCHAR(160) NOT NULL DEFAULT 'By Amount (PHP)' AFTER processing_fee_name,
  ADD COLUMN processing_fee_rate_option VARCHAR(120) NOT NULL DEFAULT 'Percent (%)' AFTER processing_fee_bracket_option,
  ADD COLUMN processing_fee_flexible TINYINT(1) NOT NULL DEFAULT 0 AFTER processing_fee_rate_option,
  ADD COLUMN processing_fee_gl_account VARCHAR(160) NULL AFTER processing_fee_flexible,
  ADD COLUMN ctr_fund_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER processing_fee_gl_account,
  ADD COLUMN insurance2_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER ctr_fund_used,
  ADD COLUMN deduction8_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER insurance2_used,
  ADD COLUMN deduction9_used VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER deduction8_used,
  ADD COLUMN service_charge_amortized VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER deduction9_used,
  ADD COLUMN savings_amortized VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER service_charge_amortized,
  ADD COLUMN amort1 VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER savings_amortized,
  ADD COLUMN amort2 VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER amort1,
  ADD COLUMN amort_date_adjustment VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER amort2,
  ADD COLUMN amort_adjust_on_holidays VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER amort_date_adjustment,
  ADD COLUMN amortization_grace_period INT UNSIGNED NULL AFTER amort_adjust_on_holidays,
  ADD COLUMN auto_debit_amortization TINYINT(1) NOT NULL DEFAULT 0 AFTER amortization_grace_period,
  ADD COLUMN savings_holdout_value DECIMAL(12,2) NULL AFTER auto_debit_amortization,
  ADD COLUMN savings_holdout_basis VARCHAR(120) NOT NULL DEFAULT 'Percent' AFTER savings_holdout_value,
  ADD COLUMN cure_period_daily INT UNSIGNED NOT NULL DEFAULT 0 AFTER savings_holdout_basis,
  ADD COLUMN cure_period_weekly INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_daily,
  ADD COLUMN cure_period_semi_monthly INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_weekly,
  ADD COLUMN cure_period_monthly INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_semi_monthly,
  ADD COLUMN cure_period_quarterly INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_monthly,
  ADD COLUMN cure_period_semi_annual INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_quarterly,
  ADD COLUMN cure_period_annual INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_semi_annual,
  ADD COLUMN cure_period_lumpsum INT UNSIGNED NOT NULL DEFAULT 0 AFTER cure_period_annual,
  ADD COLUMN enable_individual_cure_period TINYINT(1) NOT NULL DEFAULT 0 AFTER cure_period_lumpsum,
  ADD COLUMN enable_release_tagging TINYINT(1) NOT NULL DEFAULT 0 AFTER enable_individual_cure_period,
  ADD COLUMN cash_disbursed_by_teller TINYINT(1) NOT NULL DEFAULT 0 AFTER enable_release_tagging,
  ADD COLUMN security_dependent_pns TINYINT(1) NOT NULL DEFAULT 0 AFTER cash_disbursed_by_teller,
  ADD COLUMN acl_exempted TINYINT(1) NOT NULL DEFAULT 0 AFTER security_dependent_pns,
  ADD COLUMN acl_assessment VARCHAR(160) NULL AFTER acl_exempted,
  ADD COLUMN comakership_limit DECIMAL(12,2) NULL AFTER acl_assessment,
  ADD COLUMN collection_list_display VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER comakership_limit,
  ADD COLUMN collection_list_orientation VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER collection_list_display,
  ADD COLUMN balance_to_show VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER collection_list_orientation,
  ADD COLUMN reflect_date_granted TINYINT(1) NOT NULL DEFAULT 0 AFTER balance_to_show,
  ADD COLUMN reflect_loan_amount TINYINT(1) NOT NULL DEFAULT 0 AFTER reflect_date_granted,
  ADD COLUMN reflect_savings_balance TINYINT(1) NOT NULL DEFAULT 0 AFTER reflect_loan_amount,
  ADD COLUMN reflect_duedate TINYINT(1) NOT NULL DEFAULT 0 AFTER reflect_savings_balance,
  ADD COLUMN signature_on_collection_list TINYINT(1) NOT NULL DEFAULT 0 AFTER reflect_duedate,
  ADD COLUMN sms_language VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER signature_on_collection_list,
  ADD COLUMN sms_free VARCHAR(120) NOT NULL DEFAULT 'Not Used' AFTER sms_language,
  ADD COLUMN sms_show_unpaid_amorts TINYINT(1) NOT NULL DEFAULT 0 AFTER sms_free;
